### ISSUE TITLE
Github private repo

### ISSUE THREAD

**Issue by JoHuang** [artcom/git-json-api#3]
Can I use it for Github private repo?
if so, how to pass token?

Thanks

**Comment by xadh00m** [comment]
Hi JoHuang this is currently not supported but should be easy to add since it uses nodegit internally. PRs welcome.

**Comment by JoHuang** [comment]
I made a PR #5, please check it.

**Comment by xadh00m** [comment]
Has been merged and released. @JoHuang  Thank you!
