### ISSUE TITLE
npm test failed, ReferenceError: TextDecoder is not defined

### ISSUE THREAD

**Issue by JoHuang** [artcom/git-json-api#4]
The error is `ReferenceError: TextDecoder is not defined`.

However I check this PR https://github.com/facebook/jest/pull/8022/files.
It seems should be ok.

I tried to update Jest to the latest, but not works.

**Comment by xadh00m** [comment]
The issue seems to be a JEST configuration. JEST is not aware that it is running in a Node context. I´m looking into it.

**Comment by xadh00m** [comment]
This has been resolved with the latest updates.
